# horario: verao
name: Apagar imagens marcadas
jobs:
  delete_marked_folders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Apagar pastas _old (uploads/processadas e thumbnails)
      run: "for base_dir in \"uploads/processadas\" \"thumbnails\"; do\n  if [ -d\
        \ \"$base_dir\" ]; then\n    find \"$base_dir\" -maxdepth 1 -type d -name\
        \ \"*_old\" | while read dir; do\n      echo \"\U0001F5D1️ Apagando $dir\"\
        \n      rm -rf \"$dir\"\n    done\n  fi\ndone\n"
    - name: Commit das remoções
      run: "git config user.name \"Bot Limpeza\"\ngit config user.email \"bot@github.com\"\
        \ngit add uploads/processadas/ thumbnails/\nif ! git diff --cached --quiet;\
        \ then\n  git commit -m \"Apagar imagens antigas (pastas _old removidas)\"\
        \n  git push origin main\nelse\n  echo \"Nenhuma pasta _old para apagar.\"\
        \nfi\n"
'on':
  schedule:
  - cron: 30 1 * * 0
  workflow_dispatch: null
